#!/bin/bash
#
# Rsync the master in this working copy to the install on the bh1-kvm7 headnode
# GZ.
#

#set -x
set -e
TOP=$(cd $(dirname $0)/../; pwd)
NODE=root@10.2.207.2

rsync -av ${TOP}/ \
    $NODE:/opt/smartdc/imgapi-cli/ \
    --exclude "*.node" \
    --exclude .git/ \
    --exclude deps/ \
    --exclude doc/ \
    --exclude tools/ \
    --exclude tmp/ \
    --exclude build/
